-- ============================================================
-- Схема базы данных для сетевого чата (PostgreSQL)
-- ============================================================

-- (Опционально) создать схему, если требуется
 CREATE SCHEMA IF NOT EXISTS javadb;
 SET search_path TO javadb;

-- Удаление таблиц (если существуют)
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS room_messages;
DROP TABLE IF EXISTS room_members;
DROP TABLE IF EXISTS bans;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS bad_words;

-- ============================================================
-- Таблица ролей
-- ============================================================
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL
);

INSERT INTO roles (name) VALUES ('USER'), ('ADMIN');

-- ============================================================
-- Таблица пользователей
-- ============================================================
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rating INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (email, password, username) VALUES
    ('admin@chat.com', 'admin', 'admin'),
    ('user1@chat.com', 'user1', 'user1'),
    ('user2@chat.com', 'user2', 'user2'),
    ('user3@chat.com', 'user3', 'user3'),
    ('alice@chat.com', 'alice', 'Alice'),
    ('bob@chat.com', 'bob', 'Bob'),
    ('charlie@chat.com', 'charlie', 'Charlie');

select *
from users;
-- ============================================================
-- Связь пользователей и ролей
-- ============================================================
CREATE TABLE user_roles (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE (u.username = 'admin' AND r.name = 'ADMIN')
   OR (u.username IN ('user1','user2','user3','Alice','Bob','Charlie') AND r.name = 'USER');

-- ============================================================
-- Таблица банов
-- ============================================================
CREATE TABLE bans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    admin_id INT REFERENCES users(id) ON DELETE SET NULL,
    reason TEXT,                     -- вместо LONG VARCHAR
    ban_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO bans (user_id, admin_id, reason, ban_until)
SELECT u.id, a.id, 'Флуд', CURRENT_TIMESTAMP + INTERVAL '10 minutes'
FROM users u, users a
WHERE u.username = 'user2' AND a.username = 'admin';

-- ============================================================
-- Таблица комнат
-- ============================================================
CREATE TABLE rooms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    owner_id INT REFERENCES users(id) ON DELETE CASCADE,
    password VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO rooms (name, owner_id, password) VALUES
    ('Общая',        (SELECT id FROM users WHERE username = 'admin'), NULL),
    ('Техподдержка', (SELECT id FROM users WHERE username = 'admin'), 'support'),
    ('Игровая',      (SELECT id FROM users WHERE username = 'Alice'), 'game');

-- ============================================================
-- Участники комнат
-- ============================================================
CREATE TABLE room_members (
    room_id INT REFERENCES rooms(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id)
);

INSERT INTO room_members (room_id, user_id)
SELECT r.id, u.id
FROM rooms r, users u
WHERE r.name = 'Общая';

INSERT INTO room_members (room_id, user_id)
SELECT r.id, u.id
FROM rooms r, users u
WHERE r.name = 'Техподдержка' AND u.username = 'admin';

INSERT INTO room_members (room_id, user_id)
SELECT r.id, u.id
FROM rooms r, users u
WHERE r.name = 'Игровая' AND u.username IN ('Alice', 'Bob');

-- ============================================================
-- История сообщений комнат
-- ============================================================
CREATE TABLE room_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INT REFERENCES rooms(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE SET NULL,
    username VARCHAR(50),
    message TEXT,                     -- вместо LONG VARCHAR
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Всем привет!'
FROM rooms r, users u
WHERE r.name = 'Общая' AND u.username = 'admin';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Привет, админ!'
FROM rooms r, users u
WHERE r.name = 'Общая' AND u.username = 'user1';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Как дела?'
FROM rooms r, users u
WHERE r.name = 'Общая' AND u.username = 'user2';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Добро пожаловать в чат!'
FROM rooms r, users u
WHERE r.name = 'Общая' AND u.username = 'admin';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Если есть проблемы – пишите сюда.'
FROM rooms r, users u
WHERE r.name = 'Техподдержка' AND u.username = 'admin';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Давайте поиграем!'
FROM rooms r, users u
WHERE r.name = 'Игровая' AND u.username = 'Alice';

INSERT INTO room_messages (room_id, user_id, username, message)
SELECT r.id, u.id, u.username, 'Я за!'
FROM rooms r, users u
WHERE r.name = 'Игровая' AND u.username = 'Bob';

-- ============================================================
-- Рейтинги (лайки/дизлайки)
-- ============================================================
CREATE TABLE ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id INT REFERENCES users(id) ON DELETE CASCADE,
    to_user_id INT REFERENCES users(id) ON DELETE CASCADE,
    value INT NOT NULL CHECK (value IN (-1, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (from_user_id, to_user_id)
);

INSERT INTO ratings (from_user_id, to_user_id, value)
SELECT u1.id, u2.id, 1
FROM users u1, users u2
WHERE u1.username = 'Alice' AND u2.username = 'Bob';

INSERT INTO ratings (from_user_id, to_user_id, value)
SELECT u1.id, u2.id, 1
FROM users u1, users u2
WHERE u1.username = 'Bob' AND u2.username = 'Charlie';

INSERT INTO ratings (from_user_id, to_user_id, value)
SELECT u1.id, u2.id, -1
FROM users u1, users u2
WHERE u1.username = 'Charlie' AND u2.username = 'user1';

-- ============================================================
-- Таблица плохих слов
-- ============================================================
CREATE TABLE bad_words (
    word VARCHAR(50) PRIMARY KEY
);

INSERT INTO bad_words (word) VALUES
    ('дурак'), ('идиот'), ('тупой'), ('придурок'), ('дебил'),
    ('кретин'), ('ублюдок'), ('сволочь'), ('гад'), ('мерзавец'),
    ('негодяй'), ('подонок'), ('животное'), ('скотина'), ('сука'),
    ('блядь'), ('хуй'), ('пизда'), ('ебать'), ('залупа');

-- ============================================================
-- Индексы
-- ============================================================
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_last_activity ON users(last_activity);
CREATE INDEX idx_bans_user_id ON bans(user_id);
CREATE INDEX idx_rooms_name ON rooms(name);
CREATE INDEX idx_rooms_last_activity ON rooms(last_activity);
CREATE INDEX idx_room_members_room_id ON room_members(room_id);
CREATE INDEX idx_room_messages_room_id ON room_messages(room_id);
CREATE INDEX idx_ratings_to_user ON ratings(to_user_id);
CREATE INDEX idx_ratings_from_user ON ratings(from_user_id);
